name: LGBTQ+ Sydney Flatshare Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # runs every 6 hours

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 openai python-dotenv

      - name: Run the scraper
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "🚀 Running LGBTQ+ Sydney Flatshare Scraper..."
          python src/main.py

      - name: Print completion message
        run: echo "✅ Scraper run completed successfully!"
