name: LGBTQ+ Sydney Flatshare Scraper

on:
  schedule:
    # Every 30 minutes during daytime (8 AM – 8 PM, Mon – Fri)
    - cron: "*/30 8-20 * * 1-5"
    # Every 4 hours at night
    - cron: "0 21,1,5 * * *"
    # Every 8 hours on weekends
    - cron: "0 */8 * * 6,0"
  workflow_dispatch: # Allow manual trigger

jobs:
  scrape-and-analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 openai python-dotenv python-telegram-bot

      - name: Run Sydney Flatshare Scraper
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python src/main.py

      - name: Upload logs if error
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: error-logs
          path: logs/
          retention-days: 3
